import type { ProductVariant } from "@/components/ProductCard"

export const mockVariants: ProductVariant[] = [
  {
    id: "1",
    productId: "1",
    productName: "گردنبند الماسی عروس",
    productSlug: "diamond-bride-necklace",
    color: "طلایی",
    colorHex: "#B08D57",
    size: "45cm",
    price: 45000000,
    image: "/products/necklace1.jpg",
    inStock: true,
  },
  {
    id: "2",
    productId: "2",
    productName: "حلقه طلای ۱۸ عیار",
    productSlug: "18k-gold-ring",
    color: "طلایی",
    colorHex: "#D8C3A5",
    size: "۱۷",
    price: 12500000,
    image: "/products/ring1.jpg",
    inStock: true,
  },
  {
    id: "3",
    productId: "3",
    productName: "انگشتر یاقوت زهر",
    productSlug: "ruby-ring",
    color: "نقره‌ای",
    colorHex: "#C0C0C0",
    size: "۱۵",
    price: 8900000,
    image: "/products/ring2.jpg",
    inStock: true,
  },
  {
    id: "4",
    productId: "4",
    productName: "دستبند طلا با الماس",
    productSlug: "gold-diamond-bracelet",
    color: "طلایی",
    colorHex: "#B08D57",
    size: "۱۸cm",
    price: 32000000,
    image: "/products/bracelet1.jpg",
    inStock: false,
  },
  {
    id: "5",
    productId: "5",
    productName: "آویز یاقوت آبی",
    productSlug: "blue-sapphire-pendant",
    color: "نقره‌ای",
    colorHex: "#C0C0C0",
    size: "۲cm",
    price: 15600000,
    image: "/products/pendant1.jpg",
    inStock: true,
  },
  {
    id: "6",
    productId: "6",
    productName: "حلقه الماس سولیتیر",
    productSlug: "solitaire-diamond-ring",
    color: "طلایی",
    colorHex: "#D8C3A5",
    size: "۱۶",
    price: 55000000,
    image: "/products/ring3.jpg",
    inStock: true,
  },
]